/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ehu.isad;

import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.embed.swing.SwingFXUtils;
import javafx.scene.Scene;
import javafx.scene.control.ComboBox;
import javafx.scene.control.ListView;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.util.*;

public class App extends Application {
    @Override
    public void start(Stage primaryStage) throws Exception {

        primaryStage.setTitle("JavaFX ariketa");

        ComboBox comboBox = new ComboBox();

        List<String> bildumak =
                List.of("Abereak", "Paisaiak", "Kirolak");

        ObservableList<Bilduma> bildumaList =
                FXCollections.observableArrayList();

        bildumak.forEach((elem) -> {
            bildumaList.add(new Bilduma(elem));
        });

        comboBox.setItems(bildumaList);

        Map<String, List<Argazki>> bildumaMap = new HashMap<>();

        bildumaMap.put("Abereak", List.of(
                new Argazki("Elefantea", "Elefantea.jpeg"),
                new Argazki("Txakurra", "Txakurra.jpeg"),
                new Argazki("Untxia", "Untxia.jpeg")
        ));
        bildumaMap.put("Paisaiak", List.of(
                new Argazki("Oihana", "Oihana.jpeg"),
                new Argazki("Basamortua", "Basamortua.jpeg"),
                new Argazki("Elurra", "Elurra.jpeg")
        ));
        bildumaMap.put("Kirolak", List.of(
                new Argazki("Futbola", "Futbola.jpeg"),
                new Argazki("Saskibaloia", "Saskibaloia.jpeg"),
                new Argazki("Tenisa", "Tenisa.jpg")
        ));

        ObservableList<Argazki> argazkiList = FXCollections.observableArrayList();

        ListView<Argazki> listViewOfArgazki = new ListView<>(argazkiList);

        comboBox.setEditable(false);

        ImageView imageView = new ImageView();

        listViewOfArgazki.getSelectionModel().selectedItemProperty().addListener(  (observable, oldValue, newValue) -> {
            if (observable.getValue() == null) return;

            String fitx = observable.getValue().getFitx();

            try {
                imageView.setImage(lortuIrudia(fitx));
            } catch (IOException e) {
                e.printStackTrace();
            }

        });

        comboBox.setOnAction(e-> {
            listViewOfArgazki.getItems().clear();
            argazkiList.addAll(bildumaMap.get(comboBox.getValue().toString()));
        });

        VBox vbox = new VBox(comboBox, listViewOfArgazki, imageView);

        Scene scene = new Scene(vbox, 200, 120);
        primaryStage.setScene(scene);
        primaryStage.show();

    }

    private Image lortuIrudia(String location) throws IOException {

        InputStream is = getClass().getResourceAsStream("/" + location);
        BufferedImage reader = ImageIO.read(is);
        return SwingFXUtils.toFXImage(reader, null);

    }

    public static void main(String[] args) {
        Application.launch(args);
    }
}
